name: Release
on:
  release:
    types:
      - published
  workflow_dispatch: null
permissions:
  actions: none
  checks: none
  contents: write
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none
concurrency:
  group: release-${{ github.head_ref || github.ref }}
  cancel-in-progress: false
jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        uses: npm install
      - name: Build the project
        run: npm run build
      - name: Remove the read me content
        run: truncate -s 0 README.md
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
